# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY *.sln .
COPY Kumpas.AdminWeb/*.csproj ./Kumpas.AdminWeb/
RUN dotnet restore

COPY . .
WORKDIR /app/Kumpas.AdminWeb
RUN dotnet publish -c Release -o /out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /out .

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "Kumpas.AdminWeb.dll"]